//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.UserLearnCoursesRecord = new HashSet<UserLearnCoursesRecord>();
            this.CoursesComment = new HashSet<CoursesComment>();
            this.CoursesNotes = new HashSet<CoursesNotes>();
            this.CoursesQuestions = new HashSet<CoursesQuestions>();
            this.Move = new HashSet<Move>();
            this.UserLearnSectionRecord = new HashSet<UserLearnSectionRecord>();
        }
    
        public int Cou_ID { get; set; }
        public string Cou_Name { get; set; }
        public string Cou_Describe { get; set; }
        public decimal Cou_Hot { get; set; }
        public int Cou_Likes { get; set; }
        public int Cou_NotLikes { get; set; }
        public int Cou_StudyNum { get; set; }
        public int Cou_CollectNum { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Cou_Time { get; set; }
        public bool Is_UpLoading { get; set; }
        public string Extends1 { get; set; }
        public string Extends2 { get; set; }
        public string Extends3 { get; set; }
        public string Extends4 { get; set; }
    
        public virtual ICollection<UserLearnCoursesRecord> UserLearnCoursesRecord { get; set; }
        public virtual ICollection<CoursesComment> CoursesComment { get; set; }
        public virtual ICollection<CoursesNotes> CoursesNotes { get; set; }
        public virtual ICollection<CoursesQuestions> CoursesQuestions { get; set; }
        public virtual ICollection<Move> Move { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserLearnSectionRecord> UserLearnSectionRecord { get; set; }
    }
}
