//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public Move()
        {
            this.CoursesComment = new HashSet<CoursesComment>();
            this.CoursesNotes = new HashSet<CoursesNotes>();
            this.CoursesQuestions = new HashSet<CoursesQuestions>();
            this.UserLearnSectionRecord = new HashSet<UserLearnSectionRecord>();
        }
    
        public int Mov_ID { get; set; }
        public int Cou_ID { get; set; }
        public bool Is_Chapter { get; set; }
        public int Chap_ID { get; set; }
        public string Chap_Name { get; set; }
        public Nullable<int> Section_ID { get; set; }
        public string Section_Name { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual ICollection<CoursesComment> CoursesComment { get; set; }
        public virtual ICollection<CoursesNotes> CoursesNotes { get; set; }
        public virtual ICollection<CoursesQuestions> CoursesQuestions { get; set; }
        public virtual ICollection<UserLearnSectionRecord> UserLearnSectionRecord { get; set; }
    }
}
