//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigations
    {
        public Navigations()
        {
            this.NewAry = new HashSet<NewAry>();
            this.UserAry = new HashSet<UserAry>();
            this.ObjectTags = new HashSet<ObjectTags>();
            this.UserFollows = new HashSet<UserFollows>();
        }
    
        public int Nav_ID { get; set; }
        public string Nav_Name { get; set; }
        public int Ower_ID { get; set; }
        public int Nav_FollowNum { get; set; }
        public string Nav_Describe { get; set; }
        public int Nav_Type { get; set; }
        public Nullable<int> Nav_UseNum { get; set; }
        public string Extends1 { get; set; }
        public string Extends2 { get; set; }
        public string Extends3 { get; set; }
        public string Extends4 { get; set; }
    
        public virtual ICollection<NewAry> NewAry { get; set; }
        public virtual ICollection<UserAry> UserAry { get; set; }
        public virtual ICollection<ObjectTags> ObjectTags { get; set; }
        public virtual ICollection<UserFollows> UserFollows { get; set; }
    }
}
