//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewAry
    {
        public int Arr_ID { get; set; }
        public int User_ID { get; set; }
        public int Nav_ID { get; set; }
        public Nullable<double> Ary_Sco { get; set; }
    
        public virtual Navigations Navigations { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
