//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public Notes()
        {
            this.NotesComments = new HashSet<NotesComments>();
        }
    
        public int N_ID { get; set; }
        public int User_ID { get; set; }
        public string N_Title { get; set; }
        public string N_Content { get; set; }
        public string N_Content_Style { get; set; }
        public bool N_IsOriginal { get; set; }
        public int N_PageViews { get; set; }
        public int N_Likes { get; set; }
        public int N_NotLikes { get; set; }
        public System.DateTime N_Time { get; set; }
        public decimal N_Hot { get; set; }
        public int N_CollectNum { get; set; }
        public string Extends1 { get; set; }
        public string Extends2 { get; set; }
        public string Extends3 { get; set; }
        public string Extends4 { get; set; }
    
        public virtual ICollection<NotesComments> NotesComments { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
