//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionType
    {
        public OptionType()
        {
            this.ObjectTags = new HashSet<ObjectTags>();
            this.UserCollections = new HashSet<UserCollections>();
            this.UserLikes = new HashSet<UserLikes>();
            this.UserNotLikes = new HashSet<UserNotLikes>();
            this.UserPageViews = new HashSet<UserPageViews>();
            this.UserSearchRecord = new HashSet<UserSearchRecord>();
        }
    
        public int OT_ID { get; set; }
        public string OT_Name { get; set; }
        public string Extends1 { get; set; }
        public string Extends2 { get; set; }
        public string Extends3 { get; set; }
        public string Extends4 { get; set; }
    
        public virtual ICollection<ObjectTags> ObjectTags { get; set; }
        public virtual ICollection<UserCollections> UserCollections { get; set; }
        public virtual ICollection<UserLikes> UserLikes { get; set; }
        public virtual ICollection<UserNotLikes> UserNotLikes { get; set; }
        public virtual ICollection<UserPageViews> UserPageViews { get; set; }
        public virtual ICollection<UserSearchRecord> UserSearchRecord { get; set; }
    }
}
