//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceInfo
    {
        public ResourceInfo()
        {
            this.ResourceComment = new HashSet<ResourceComment>();
        }
    
        public int R_ID { get; set; }
        public int R_Type { get; set; }
        public int User_ID { get; set; }
        public string R_Name { get; set; }
        public string R_Content { get; set; }
        public System.DateTime R_Time { get; set; }
        public int R_DownLoad { get; set; }
        public decimal R_Hot { get; set; }
    
        public virtual ICollection<ResourceComment> ResourceComment { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
