//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZULIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Answers = new HashSet<Answers>();
            this.Courses = new HashSet<Courses>();
            this.CoursesAnswers = new HashSet<CoursesAnswers>();
            this.CoursesComment = new HashSet<CoursesComment>();
            this.CoursesNotes = new HashSet<CoursesNotes>();
            this.CoursesQuestions = new HashSet<CoursesQuestions>();
            this.Follow = new HashSet<Follow>();
            this.Follow1 = new HashSet<Follow>();
            this.NewAry = new HashSet<NewAry>();
            this.Notes = new HashSet<Notes>();
            this.NotesComments = new HashSet<NotesComments>();
            this.Questions = new HashSet<Questions>();
            this.ResourceComment = new HashSet<ResourceComment>();
            this.ResourceInfo = new HashSet<ResourceInfo>();
            this.UserAry = new HashSet<UserAry>();
            this.UserCollections = new HashSet<UserCollections>();
            this.UserFollows = new HashSet<UserFollows>();
            this.UserLearnCoursesRecord = new HashSet<UserLearnCoursesRecord>();
            this.UserLearnSectionRecord = new HashSet<UserLearnSectionRecord>();
            this.UserLikes = new HashSet<UserLikes>();
            this.UserNotLikes = new HashSet<UserNotLikes>();
            this.UserPageViews = new HashSet<UserPageViews>();
            this.UserSearchRecord = new HashSet<UserSearchRecord>();
        }
    
        public int User_ID { get; set; }
        public string User_Account { get; set; }
        public string User_Password { get; set; }
        public string User_NickName { get; set; }
        public int User_Priority { get; set; }
        public int User_Priority_Now { get; set; }
        public Nullable<System.DateTime> User_LastLoginTime { get; set; }
        public string Extends1 { get; set; }
        public string Extends2 { get; set; }
        public string Extends3 { get; set; }
        public string Extends4 { get; set; }
        public string User_Email { get; set; }
        public string User_Gender { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual ICollection<CoursesAnswers> CoursesAnswers { get; set; }
        public virtual ICollection<CoursesComment> CoursesComment { get; set; }
        public virtual ICollection<CoursesNotes> CoursesNotes { get; set; }
        public virtual ICollection<CoursesQuestions> CoursesQuestions { get; set; }
        public virtual ICollection<Follow> Follow { get; set; }
        public virtual ICollection<Follow> Follow1 { get; set; }
        public virtual ICollection<NewAry> NewAry { get; set; }
        public virtual ICollection<Notes> Notes { get; set; }
        public virtual ICollection<NotesComments> NotesComments { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Priority Priority1 { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<ResourceComment> ResourceComment { get; set; }
        public virtual ICollection<ResourceInfo> ResourceInfo { get; set; }
        public virtual ICollection<UserAry> UserAry { get; set; }
        public virtual ICollection<UserCollections> UserCollections { get; set; }
        public virtual ICollection<UserFollows> UserFollows { get; set; }
        public virtual ICollection<UserLearnCoursesRecord> UserLearnCoursesRecord { get; set; }
        public virtual ICollection<UserLearnSectionRecord> UserLearnSectionRecord { get; set; }
        public virtual ICollection<UserLikes> UserLikes { get; set; }
        public virtual ICollection<UserNotLikes> UserNotLikes { get; set; }
        public virtual ICollection<UserPageViews> UserPageViews { get; set; }
        public virtual ICollection<UserSearchRecord> UserSearchRecord { get; set; }
    }
}
